name: advanced_course
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
